### PR TITLE
Change command name from build to electron-builder

### PR DESCRIPTION
**Pull request by Trip09**
Change command name from build to electron-builder

Current build is broken and it's not being able to build the files.

Also is required to do a new build for tusk to work with latest evernote upgrade.

This will close
https://github.com/klaussinani/tusk/issues/255
https://github.com/klaussinani/tusk/issues/257
https://github.com/klaussinani/tusk/issues/259

### CODE REVIEW

**Comment by mclaser** [comment]
I have the same issue on Pop_OS, and don't really understand how to get myself (Tusk) going again.  I installed via snap and tried 'snap refresh tusk' but it reports No Updates Available.  With my marginal understanding of these things does that mean that your change is awaiting a push/update to the snap store so I can get the change?  Is there another way for me to resolve this?    I sure would like to continue using the app!

**Comment by morganchenjp** [comment]
Had same issue. 
@klaussinani  can you help review this change ? and maybe release a fix. 
Used Tusk on Linux for almost half year and really love it. 
thanks.

**Comment by notredruide** [comment]
Same problem on brand new install to Ubuntu 18.04 via Ubuntu Software. Blank screen, no way to enter Evernote credentials. Log out does nothing. Back to the browser client I guess ...

**Comment by Trip09** [comment]
This repo is dead the maintainer doesn't respond to PR. I'm supporting the project in my Repo. compiled files and ready to use in: 
https://github.com/Trip09/tusk/releases/tag/v1.0.0

**Pull request closed without merging**
